### ISSUE TITLE
Error on device update

### ISSUE THREAD

**Issue by abeksis** [custom-cards/aftership-card#5]
```
2019-05-26 17:28:13 ERROR (MainThread) [homeassistant.components.sensor] aftership: Error on device update!
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 261, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/app/homeassistant/helpers/entity.py", line 375, in async_device_update
    await self.async_update()
  File "/usr/src/app/homeassistant/components/aftership/sensor.py", line 190, in async_update
    'last_checkpoint': track['checkpoints'][-1]
```

**Comment by 100lv** [comment]
I have the same issue :-(

**Comment by ludeeus** [comment]
This is an issue with the component, not this card, report this to HA's issue tracker.
